import {
  DEFAULT_NAME_COLOR,
  NAME_COLOR_MAP,
  NAME_COLOR_OPTIONS,
} from './nameColors';

export const DEFAULT_KADER_COLOR = DEFAULT_NAME_COLOR;
export const KADER_COLOR_OPTIONS = NAME_COLOR_OPTIONS;
export const KADER_COLOR_MAP = NAME_COLOR_MAP;
